[package]
name = "acnd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console_engine = "2.*.*"
euclid = "0.*.*"
fastrand = "1.*.*"
